version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - depguard
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: ST1003
      - path: (.+)\.go$
        text: ST1000
      - path: (.+)\.go$
        text: don't use an underscore in package name
      - path: (.+)\.go$
        text: declaration of "(err|ctx)" shadows declaration at
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
