name: CI
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ${{ matrix.os }} Go (${{ matrix.go }})
    timeout-minutes: 5
    strategy:
      matrix:
        go: ['stable']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Check out code into the Go module directory
        uses: actions/checkout@v6

      - name: Check go version
        run: make info

      - name: Go Format
        run: make format-check

      - name: Go Tidy
        run: make tidy

      - name: Go Mod Verify
        run: make verify

      - name: Install linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11
          install-only: true

      - name: Run linter
        run: make lint

      - name: Run tests
        run: |
          make test
